import type { Artist } from '../types/content';

const images = import.meta.glob('@/assets/images/**/*', { eager: true, query: '?url', import: 'default' });
const image = (name: string) =>
  images[`/src/assets/images/${name}`] as string;

// TODO: this content should go in DynamoDB entries... accessed by tempurawaves-app
// TODO: image content should go in S3...
export const artists: Record<string, Artist> = {
  'dj-shuvohl': {
    slug: 'dj-shuvohl',
    name: 'DJ Shuvohl',
    group: 'producers',
    tagline: 'Electronic, melodic, experimental',
    bio: 'Primary producer of Tempura Waves. DJ Shuvohl crafts electronic melodic and experimental music rooted in lush green botanical aesthetics — synthesizers woven through organic textures like vines through forest canopy.',
    themeId: 'djShuvohl',
    image: image('dj-shuvohl/IMG_7963.jpg'),
    albums: [
      {
        title: 'The Darkness of Bright Auroras',
        year: 2006,
        cover: image('dj-shuvohl/darkness_bright.svg'),
        tracks: [
          { title: 'Soak Your Stereo', duration: '3:21' },
          { title: 'SparX', duration: '4:12' },
          { title: 'Drag into the Night ~ITS~', duration: '2:46' },
          { title: 'Demo Aquarium ~Clockwork Mix~', duration: '3:00' },
          { title: 'Shutters', duration: '2:40', feat: { name: 'jacobplaylists', slug: 'jacobplaylists' } },
          { title: 'We Forgot', duration: '0:58', feat: { name: 'Jaint', slug: 'jaint' } },
          { title: 'O', duration: '3:03' },
          { title: 'Gizmo Tent', duration: '2:44' },
          { title: 'Phantasms', duration: '5:22' },
          { title: 'Gizmo Box', duration: '3:43' },
          { title: 'Rain of Death', duration: '5:27', feat: { name: 'Mike Templet', slug: 'mike-templet' } },
          { title: 'Metallic Orchestration (Quicky)', duration: '1:10', feat: { name: 'jacobplaylists', slug: 'jacobplaylists' } },
          { title: 'Olive Sky', duration: '4:58', feat: { name: 'jacobplaylists', slug: 'jacobplaylists' } },
          { title: 'C-Defense', duration: '4:51' },
          { title: 'Depressing Messages', duration: '3:40' },
          { title: 'Mexameri', duration: '2:14', feat: { name: 'jacobplaylists', slug: 'jacobplaylists' } },
          { title: 'June Gloom ~Intro~', duration: '0:24' },

        ],
      },
      {
        title: 'A Short Hope',
        year: 2008,
        cover: image('dj-shuvohl/short_hope.svg'),
        tracks: [
          { title: 'WWG', duration: '2:44', feat: { name: 'Hannah', slug: 'hannah' } },
          { title: 'Groove-It', duration: '3:57' },
          { title: 'Malachi', duration: '7:11' },
          { title: 'SparX (Dilapidated Mix)', duration: '4:18' },
          { title: 'Wir Werden Frei Sein', duration: '6:28' },
          { title: 'Homeboys from the Dark', duration: '2:32' },
          { title: 'French Dip', duration: '3:22', feat: { name: 'Mike Templet', slug: 'mike-templet' } },
          { title: 'Artichoke Rhapsody', duration: '3:02' },
          { title: 'Fruit Cake', duration: '5:24', feat: { name: 'jacobplaylists', slug: 'jacobplaylists' } },
          { title: 'Vanquished!', duration: '5:05' },
          { title: 'Interlude - Shutters', duration: '1:44', feat: { name: 'jacobplaylists', slug: 'jacobplaylists' } },
          { title: 'Secret', duration: '4:14' },
          { title: 'Crossing the Deep', duration: '3:35' },
          { title: 'Sing the Second Chime', duration: '2:49' },
          { title: 'Freska ~Memories of the Younger Years~', duration: '3:26' },
        ],
      },
      {
        title: 'Integrated Insanity',
        year: 2008,
        cover: image('dj-shuvohl/integrated_insanity.svg'),
        tracks: [
          { title: 'Fader', duration: '2:26' },
          { title: 'Frank Galactagon!', duration: '3:40' },
          { title: 'Pill Poppers', duration: '3:42' },
          { title: 'Carbon Killers', duration: '3:46' },
          { title: 'Platoon', duration: '2:47' },
          { title: 'Sine Waves', duration: '4:54' },
          { title: 'Warp Life', duration: '3:48' },
          { title: 'King Renzo\'s Melody Act I', duration: '3:54' },
          { title: 'Lancaster', duration: '3:20' },
          { title: 'Rushing Around', duration: '4:21' },
          { title: 'Continuum', duration: '4:47' },
          { title: 'Drag [Only Her] into the Night', duration: '8:27' },
          { title: 'Left Bound', duration: '6:25' },
          { title: 'Level 3', duration: '5:01' },
          { title: 'Headrush', duration: '3:10' },
          { title: 'Esoteric Mind', duration: '3:19' },
          { title: 'Last Year (Dec)', duration: '2:18' },
          { title: 'Saturated Air', duration: '6:36' },
        ],
      },
      {
        title: 'pH Era',
        year: 2008,
        cover: image('dj-shuvohl/ph_era.svg'),
        tracks: [
          { title: 'Cellular Prism', duration: '2:45' },
          { title: 'Chocolate Mystery', duration: '2:00' },
          { title: 'Happy Mutilation', duration: '3:36' },
          { title: 'My Palindrome', duration: '3:12' },
          { title: '312 (Waiting for you...)', duration: '4:45' },
          { title: 'Running Stairs', duration: '6:13' },
          { title: 'Basking Warmth', duration: '4:48' },
          { title: 'Integrable', duration: '7:22' },
          { title: 'Irrationality', duration: '4:18' },
          { title: 'Power of Hydrogen', duration: '4:36' },
          { title: 'King Renzo\'s Melody Act II', duration: '3:55' },
          { title: 'I See Legs', duration: '8:10' },
          { title: 'Differentiation', duration: '2:04' },
          { title: 'Fwa!', duration: '4:16' },
          { title: 'Held Together', duration: '5:20' },
          { title: 'Opium and Milk', duration: '3:54' },
          { title: 'Alias 213', duration: '3:39' },
          { title: 'Last Year (Jan)', duration: '1:52' },
          { title: 'Vengeance', duration: '3:08' },
        ],
      },
      {
        title: 'F Your Face',
        year: 2009,
        cover: image('dj-shuvohl/face.svg'),
        tracks: [
          { title: 'Back to Basics', duration: '4:12' },
          { title: 'Gooba Gabba', duration: '4:46' },
          { title: 'Dreaming That It Isn\'t a Dream', duration: '3:42' },
          { title: 'World\'s Fastest Bookstore', duration: '2:46' },
          { title: 'You Blocked Me, GathaTwin', duration: '2:49' },
          { title: 'Tolchok Valentine', duration: '6:28' },
          { title: 'Trashcan Electrix', duration: '5:35' },
          { title: 'My Song Titles Are Longer than an...', duration: '2:49' },
          { title: 'Electric Eel (The Love Tree)', duration: '5:07' },
          { title: 'Smoking Banshees', duration: '6:01' },
          { title: 'Plinths', duration: '2:55' },
          { title: 'Malisious', duration: '3:56' },
          { title: 'Socially Inept Fool', duration: '5:38' },
          { title: 'Rice Transformation', duration: '2:41' },
          { title: 'Adventuring with the Plaid-Checkered Scarf', duration: '7:37' },
          { title: 'Electric *FRAGGIN* Eel', duration: '2:34' },
          { title: 'Word Salad', duration: '4:08' },
          { title: 'SSM', duration: '4:05' },
          { title: 'Forget Your Face', duration: '1:57' },
        ],
      },
      {
        title: 'AiC',
        year: 2011,
        cover: image('dj-shuvohl/aic.svg'),
        tracks: [
          { title: 'Greetings', duration: '2:46' },
          { title: 'Chrome Bells', duration: '6:27' },
          { title: 'Choo Choo Train', duration: '4:42' },
          { title: 'Purple Is the New Green', duration: '4:26' },
          { title: 'MB&S', duration: '3:35' },
          { title: 'Ham and Eggs', duration: '2:46' },
          { title: 'Zap Zap!', duration: '1:51' },
          { title: 'Largobytes', duration: '1:53' },
          { title: 'Impossibility', duration: '1:53' },
          { title: 'Platoon', duration: '1:22' },
          { title: 'Wiremom', duration: '3:46' },
          { title: 'Win', duration: '2:44' },
          { title: 'Boogery Fwa!', duration: '1:37' },
          { title: 'Largobytes (Reprise)', duration: '1:17' },
          { title: 'Fable AM', duration: '3:52' },
          { title: 'Made in Taiwan', duration: '4:29' },
          { title: 'Singular', duration: '5:53' },
          { title: 'Ambulance', duration: '4:31' },
          { title: 'Her Other Side', duration: '4:33' },
          { title: 'TAGs', duration: '4:33' },
          { title: 'Truncation', duration: '3:58' },
          { title: 'Honor', duration: '2:59' },
          { title: 'Super Sadistry', duration: '3:09' },
          { title: 'Nagbibilang', duration: '6:14' },
          { title: 'Broken', duration: '3:30' },
        ],
      },
      {
        title: 'A Series of Simple Patterns',
        year: 2013,
        cover: image('dj-shuvohl/simple_patterns.jpg'),
        tracks: [
          { title: 'Solitary', duration: '4:34' },
          { title: 'Polar North', duration: '3:09' },
          { title: 'Disturbance', duration: '2:49' },
          { title: 'Circumambulation', duration: '2:50' },
          { title: 'Canticle', duration: '5:05' },
          { title: 'Eskimo Pi', duration: '2:43' },
          { title: '1592', duration: '2:19' },
          { title: 'Tropical Bump', duration: '4:51' },
          { title: 'Fading Joy', duration: '3:59' },
          { title: 'Sth', duration: '3:46' },
          { title: 'Default', duration: '1:57' },
          { title: 'Andrea Says "Platypus"', duration: '3:52' },
          { title: 'Cry Cry Chimera', duration: '4:26' },
          { title: 'Hive', duration: '2:46' },
          { title: 'Sagebrush', duration: '3:26' },
          { title: 'Coagulation', duration: '3:45' },
          { title: 'Coughstyle', duration: '5:00' },
          { title: 'Amnesia Town', duration: '4:43' },
          { title: 'Krabby / Kingler [Bonus Track]', duration: '0:51' },
        ],
      },
      {
        title: 'Rose',
        year: 2023,
        cover: image('dj-shuvohl/rose.jpg'),
        tracks: [
          { title: 'Thorns', duration: '2:28' },
          { title: 'Vegetation', duration: '3:08' },
          { title: 'Roots', duration: '3:32' },
          { title: 'Blight', duration: '1:24' },
          { title: 'Thorns II', duration: '2:43' },
          { title: 'Stalks', duration: '3:28' },
          { title: 'Fibers', duration: '3:51' },
          { title: 'Leaves', duration: '1:40' },
          { title: 'Petals', duration: '3:40' },
          { title: 'Pollen', duration: '2:38' },
          { title: 'Buds', duration: '1:37' },
          { title: 'Rain', duration: '4:55', feat: { name: 'Junipher', slug: 'junipher' } },
          { title: 'Vegetation II', duration: '1:31' },
          { title: 'Rosette', duration: '4:12', feat: {name: 'Onionoid', slug: 'onionoid' } },
          { title: 'Seeds', duration: '1:48', feat: {name: 'Onionoid', slug: 'onionoid' }  },
        ],
      },
      {
        title: '22 / 33',
        year: 2025,
        cover: image('dj-shuvohl/22_33.jpg'),
        tracks: [
          { title: 'Start', duration: '3:52' },
          { title: 'Centripetal', duration: '4:22' },
          { title: 'The Second Death', duration: '1:04' },
          { title: 'Magnetic North', duration: '4:16' },
          { title: 'Symphony of Asparagus', duration: '3:27' },
          { title: 'Base 10', duration: '2:59' },
          { title: '48 Before Foundations', duration: '1:14' },
          { title: 'Raycaster', duration: '3:36' },
          { title: 'False Start', duration: '3:12' },
          { title: 'Sirens of Ficus', duration: '2:57' },
          { title: 'Sleeping Stairs', duration: '5:06' },
          { title: 'Sweet Dreams', duration: '1:26' },
          { title: 'Seismic Phantom (I. Drained, II. Random Walk, III. Purpose)', duration: '5:44' },
          { title: 'Olive Skyway', duration: '4:54' },
          { title: 'False Peak', duration: '6:11' },
        ],
      },
      {
        title: 'Innocent Man',
        year: 2026,
        cover: image('dj-shuvohl/innocent_man.jpg'),
        tracks: [
          { title: 'Spaghetti Sauce in a Bowl', duration: '2:01' },
          { title: 'Innocent Man', duration: '2:41' },
          { title: 'Season 1 ~Afternoon Warp~', duration: '3:51' },
          { title: 'Pelican State', duration: '1:29', feat: { name: 'DJ Mellow-D', slug: 'dj-mellow-d' } },
          { title: 'Last 5min of the Weekly', duration: '1:14', feat: { name: 'Ernieshmitz', slug: 'ernieshmitz' } },
          { title: 'Beautiful Note (Interlude)', duration: '1:15' },
          { title: 'Waiting...', duration: '1:55' },
          { title: 'Destiny?', duration: '3:03' },
          { title: 'The Ceiling (Uh-Oh!)', duration: '3:49' },
          { title: 'Abandon', duration: '1:27' },
          { title: 'Season 2 ~Half of a Year~', duration: '3:50' },
          { title: 'Desert Bone', duration: '2:11', feat: { name: 'DDoS_Joce', slug: 'ddos-joce' } },
          { title: 'Pizza', duration: '1:38' },
          { title: 'Beautiful Dream (Interlude)', duration: '1:43' },
          { title: 'The Scripts', duration: '2:05', feat: { name: 'Ernieshmitz', slug: 'ernieshmitz' } },
          { title: 'Garden of Superstition', duration: '3:55' },
          { title: 'Photobooth', duration: '4:03' },
          { title: 'Innocent Cats [Bonus Track]', duration: '0:48' },
          { title: 'Essenell [Bonus Track]', duration: '1:09' },
          { title: 'Super Bowl [Bonus Track]', duration: '0:36' },
          { title: 'Pops [Bonus Track]', duration: '1:01' },
        ],
      },
      {
        title: 'Toxins',
        year: 2026,
        cover: image('dj-shuvohl/toxins.jpg'),
        tracks: [
          { title: 'I Deserve Equipment', duration: '3:19' },
          { title: 'Introducing My Friends', duration: '2:58' },
          { title: 'Focus', duration: '3:42' },
          { title: 'Anxiety', duration: '2:14' },
          { title: 'Rumination', duration: '3:44', feat: { name: 'Onionoid', slug: 'onionoid' } },
          { title: 'Change Is Sickening', duration: '1:26' },
          { title: 'Mildew', duration: '1:54' },
          { title: 'My Shelter', duration: '2:44' },
          { title: 'Nostalgic Daydreams', duration: '3:12' },
          { title: 'Bedrotting', duration: '2:31' },
          { title: 'My Indecision, Your Impatience', duration: '2:14' },
          { title: 'After Work Smoke Break', duration: '2:20' },
          { title: 'Neglect', duration: '0:48' },
          { title: 'Ego Death', duration: '1:28' },
          { title: 'The Core', duration: '2:27' },
          { title: 'Temperament', duration: '3:07' },
          { title: 'Sayonara, Me!', duration: '2:33' },
        ],
      },  
      {
        title: 'Photosynthesis',
        year: 2025,
        cover: image('dj-shuvohl/photosynthesis.svg'),
        tracks: [
          { title: 'Chlorophyll Dreams', duration: '5:23' },
          { title: 'Root System', duration: '4:47' },
          { title: 'Canopy Light', duration: '6:12' },
          { title: 'Moss Frequency', duration: '3:58' },
        ],
      },
      {
        title: 'Greenhouse Sessions',
        year: 2024,
        cover: image('dj-shuvohl/greenhouse.svg'),
        tracks: [
          { title: 'Humid Air', duration: '4:31' },
          { title: 'Fern Loop', duration: '5:05' },
          { title: 'Terrarium', duration: '7:20' },
        ],
      },
    ],
    compilations: [
      {
        title: 'Megamix',
        year: 2025,
        cover: image('dj-shuvohl/megamix.jpg'),
        tracks: [
          { title: 'Soak Your Stereo', duration: '2:18' },
          { title: 'My Palindrome', duration: '1:48' },
          { title: '312 (Waiting for You)...', duration: '1:36' },
          { title: 'Running Stairs', duration: '1:59' },
          { title: 'C-Defense', duration: '2:14' },
          { title: 'Lancaster', duration: '2:17' },
          { title: 'Olive Sky', duration: '2:23' },
          { title: 'Word Salad', duration: '1:12' },
          { title: 'Purple Is the New Green', duration: '2:10' },
          { title: 'Sine Waves / Warp Life', duration: '2:13' },
          { title: 'True North', duration: '5:08' },
          { title: 'Fruit Cake', duration: '2:44' },
          { title: 'Wir Werden Frei Sein', duration: '2:02' },
          { title: 'Ascending Filtration', duration: '2:34' },
          { title: 'Day After Snow', duration: '2:54' },
          { title: 'Crossing the Deep', duration: '1:45' },
          { title: 'Frank Galactagon!', duration: '1:54' },
          { title: 'World\'s Fastest Bookstore', duration: '1:42' },
          { title: 'Socially Inept Fool', duration: '2:58' },
          { title: 'Made in Taiwan ~陳~', duration: '4:21' },
        ],
      },
    ]
  },

  'dj-mellow-d': {
    slug: 'dj-mellow-d',
    name: 'DJ Mellow-D',
    group: 'producers',
    tagline: 'Folk, psych rock, melodic trance & chiptune',
    bio: 'Producer associated with Rascal Stew, a comic punk band. DJ Mellow-D spans folk, psychedelic rock, melodic trance, trip hop, and chiptune — visualized through fractal patterns in orange, brown, and teal.',
    themeId: 'djMellowD',
    image: image('dj-mellow-d/profile.svg'),
    albums: [
      {
        title: 'Fractal Drift',
        year: 2025,
        cover: image('dj-mellow-d/fractal-drift.svg'),
        tracks: [
          { title: 'Mandelbrot Morning', duration: '5:44' },
          { title: 'Teal Horizon', duration: '4:18' },
          { title: 'Orange Spiral', duration: '6:33' },
        ],
      },
      {
        title: 'Rascal Stew Sessions',
        year: 2023,
        cover: image('dj-mellow-d/rascal-stew.svg'),
        tracks: [
          { title: 'Punk Comic Interlude', duration: '3:12' },
          { title: 'Folk Fracture', duration: '4:56' },
          { title: 'Trip Hop Tale', duration: '5:21' },
        ],
      },
    ],
  },

  ernieshmitz: {
    slug: 'ernieshmitz',
    name: 'Ernieshmitz',
    group: 'producers',
    tagline: 'Dubstep, riddim & chiptune',
    bio: 'Producer specializing in dubstep, riddim, and chiptune. Ernieshmitz brings an electronic 8-bit videogame aesthetic — neon grids, pixel borders, and heavy bass drops rendered in retro digital glory.',
    themeId: 'ernieshmitz',
    image: image('ernieshmitz/profile.svg'),
    albums: [
      {
        title: '8-Bit Annihilation',
        year: 2025,
        cover: image('ernieshmitz/8bit-annihilation.svg'),
        tracks: [
          { title: 'Boss Fight', duration: '3:45' },
          { title: 'Riddim Runner', duration: '4:02' },
          { title: 'Coin Collect', duration: '2:58' },
          { title: 'Game Over (Remix)', duration: '5:11' },
        ],
      },
      {
        title: 'Pixel Wobble',
        year: 2024,
        cover: image('ernieshmitz/pixel-wobble.svg'),
        tracks: [
          { title: 'Drop Code', duration: '3:33' },
          { title: 'Chiptune Chaos', duration: '4:44' },
        ],
      },
    ],
  },

  jacobplaylists: {
    slug: 'jacobplaylists',
    name: 'Jacobplaylists',
    group: 'collaborators',
    tagline: 'RnB, chill, pop & ballads',
    bio: 'Producer of RnB, chill, pop, and ballads. Jacobplaylists paints sonic landscapes in pink and aquatic tones — stars, sparkles, and gentle waves of melody drifting through midnight water.',
    themeId: 'jacobplaylists',
    image: image('jacobplaylists/profile.svg'),
    albums: [
      {
        title: 'Starlit Currents',
        year: 2025,
        cover: image('jacobplaylists/starlit-currents.svg'),
        tracks: [
          { title: 'Pink Tide', duration: '4:22' },
          { title: 'Sparkle Ballad', duration: '5:01' },
          { title: 'Aquatic RnB', duration: '3:47' },
        ],
      },
      {
        title: 'Chill Constellation',
        year: 2024,
        cover: image('jacobplaylists/chill-constellation.svg'),
        tracks: [
          { title: 'Floating Stars', duration: '4:15' },
          { title: 'Pop Current', duration: '3:33' },
        ],
      },
    ],
  },

  soficchi: {
    slug: 'soficchi',
    name: 'Soficchi',
    group: 'collaborators',
    tagline: 'Vibrant vocalist — RnB & operatic range',
    bio: 'A vibrant vocalist with RnB and operatic range who also plays viola. Soficchi\'s world is cute Japanese-inspired imagery — sparkles, pastel dreams, and the occasional lethargic rat companion.',
    themeId: 'soficchi',
    image: image('soficchi/profile.svg'),
    albums: [
      {
        title: 'Kawaii Lullaby',
        year: 2025,
        cover: image('soficchi/kawaii-lullaby.svg'),
        tracks: [
          { title: 'Sparkle Viola', duration: '4:38' },
          { title: 'Operatic Dawn', duration: '6:02' },
          { title: 'Lazy Rat Nap', duration: '3:21' },
        ],
      },
      {
        title: 'Pastel Opera',
        year: 2024,
        cover: image('soficchi/pastel-opera.svg'),
        tracks: [
          { title: 'Sakura Song', duration: '5:14' },
          { title: 'RnB Reverie', duration: '4:09' },
        ],
      },
    ],
  },

  junipher: {
    slug: 'junipher',
    name: 'Junipher',
    group: 'collaborators',
    tagline: 'Gentle vocals & trumpet',
    bio: 'Vocalist with gentle and calming vocals who also plays trumpet. Junipher loves green landscapes and dogs — her music feels like a warm walk through a sunlit park with a loyal companion at your side.',
    themeId: 'junipher',
    image: image('junipher/profile.svg'),
    albums: [
      {
        title: 'Green Park Serenade',
        year: 2025,
        cover: image('junipher/green-park.svg'),
        tracks: [
          { title: 'Trumpet at Dawn', duration: '4:51' },
          { title: 'Dog Days', duration: '3:44' },
          { title: 'Calm Green', duration: '5:28' },
        ],
      },
      {
        title: 'Gentle Horns',
        year: 2024,
        cover: image('junipher/gentle-horns.svg'),
        tracks: [
          { title: 'Soft Breeze', duration: '4:03' },
          { title: 'Puppy Love', duration: '3:56' },
        ],
      },
    ],
  },

  onionoid: {
    slug: 'onionoid',
    name: 'Onionoid',
    group: 'collaborators',
    tagline: 'Violin — rocks, gems & running water',
    bio: 'Violin player whose visual world is rocks, mined gemstones, and running water. Onionoid\'s performances crystallize into amethyst and sapphire tones, flowing like a stream over ancient stone.',
    themeId: 'onionoid',
    image: image('onionoid/profile.svg'),
    albums: [
      {
        title: 'Gemstone Current',
        year: 2025,
        cover: image('onionoid/gemstone-current.svg'),
        tracks: [
          { title: 'Amethyst Flow', duration: '5:17' },
          { title: 'River Stone', duration: '4:42' },
          { title: 'Crystal Violin', duration: '6:05' },
        ],
      },
      {
        title: 'Mined Melodies',
        year: 2024,
        cover: image('onionoid/mined-melodies.svg'),
        tracks: [
          { title: 'Sapphire Stream', duration: '4:28' },
          { title: 'Granite Echo', duration: '5:33' },
        ],
      },
    ],
  },
};

export function getArtist(slug: string): Artist | undefined {
  return artists[slug];
}

export function getArtistsBySlugs(slugs: readonly string[]): Artist[] {
  return slugs.map((slug) => artists[slug]).filter(Boolean) as Artist[];
}

export function getArtistPath(artist: Artist): string {
  return `/artists/${artist.slug}`;
}
